Performances/urls.py
from django.conf.urls import url 
from . import views

app_name = 'Performances'

urlpatterns=[
# url(r'^$', views.index, name='index'),
# url(r'^AddSongPage', vie.ws.AddSongPage, name='AddSongPage'),
url(r'test', views.test, name="test"),
url(r'^', views.Performances, name='Performances'),
# url(r'^AddSong', views.AddSong, name='AddSong'),
# url(r'^MainPage', views.MainPage, name='MainPage'),
# url(r'^Login', views.Login, name='Login' ),
# url(r'^Logout', views.Logout, name='Logout'),

]

Repertoire/urls.py
from django.conf.urls import url 
from . import views

app_name = 'Repertoire'

urlpatterns=[
# url(r'^$', views.index, name='index'),
# url(r'^AddSongPage', vie.ws.AddSongPage, name='AddSongPage'),
url(r'^$', views.Repertoire, name='Repertoire'),
url(r'^AddSong', views.AddSong, name='AddSong'),
# url(r'^MainPage', views.MainPage, name='MainPage'),
url(r'^Login', views.Login, name='Login' ),
url(r'^Logout', views.Logout, name='Logout'),

]

RepertoireManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# import Repertoire.views as Rep
# from django.contrib.auth import views as auth_views
# import django as django



urlpatterns = [
    url(r'^Repertoire/', include('Repertoire.urls')),
    url(r'^Performances/', include('Performances.urls')),
    url(r'^[aA]dmin/', admin.site.urls),
    # url(r'^login', auth_views.login, name='login' ), 
    # url(r'^Repertoire/', Rep.Repertoire, name="Repertoire" ),
   
]
    

Performances/models.py
from django.db import models
# from 
# Create your models here.

from Repertoire.models import song

class Performance(models.Model):
	def __str__(self):
		return self.name

	name = models.CharField(max_length=200)
	songs = models.ManyToManyField(song, through='SongOrder')
	date = models.DateField(null=True, blank=True)

class SongOrder(models.Model):
	def __str__(self):
		return self.songs.name

	songs = models.ForeignKey(song, on_delete=models.CASCADE)
	performance = models.ForeignKey(Performance, on_delete=models.CASCADE)
	orderInPerformance = models.IntegerField(null=True, blank=True)

Repertoire/models.py
from django.db import models

# Create your models here.

class song(models.Model):
	name = models.CharField(max_length=200)
	lyrics = models.TextField(null=True, blank=True)
	audioFile = models.FileField(upload_to='audioRepository', null=True, blank=True)

	def __str__(self):
		return self.name

player/models.py
from django.db import models

# Create your models here.

Performances/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Performance, SongOrder
# from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.

# def Performances(request):
# 	return HttpResponse("Yeeeey")

def Performances(request):
	if request.user.is_authenticated():
		# CurrentSelection = Performance.objects.get(pk=2)
		Performances = Performance.objects.all().order_by('date')
		CurrentSelection = Performances[0]
		Songs = SongOrder.objects.filter(performance=2).order_by('orderInPerformance')
		# Songs = SongOrder.objects.all()
		return render(request, 'Performances/Performances.html', { 'username' : request.user, 'loggedin' : True, 'Performances' : Performances, 'Songs' : Songs, 'CurrentSelection': CurrentSelection} )
	else:
		return render(request, 'Performances/Performances.html', { 'username': request.user, 'loggedin' : False } )

def test(request):
	return HttpResponse("Yeeeey")

Repertoire/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import song
# from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def Repertoire(request):
	if request.user.is_authenticated():		
		SongsInRepertoire = song.objects.all().order_by('name')
		return render(request, 'Repertoire/repertoire.html', { 'username' : request.user, 'loggedin' : True, 'songs' : SongsInRepertoire} )
	else:
		return render(request, 'Repertoire/repertoire.html', { 'username': request.user, 'loggedin' : False } )
  	
def Login(request):	
	username = request.POST.get('username')
	password = request.POST.get('password')
	user = authenticate(username=username, password=password)
	if user is not None:
		login(request, user)
	return HttpResponseRedirect(reverse("Repertoire:Repertoire"))

def Logout(request):
	logout(request)
	return HttpResponseRedirect(reverse("Repertoire:Repertoire"))

def AddSong(request):
	s = song(name=request.POST['SongName'])
	s.save()
	return HttpResponseRedirect(reverse("Repertoire:Repertoire"))

player/views.py
from django.shortcuts import render

# Create your views here.

Performances/templates/Performances/Performances.html
{% load static %}

<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Performances</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="{% static 'Repertoire/style.css' %}" />

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>

<body>
</body>
</html>


<div class="header">


	<form action="{% url 'Repertoire:Login' %}" method='post'>
	
	{% if loggedin %}
		Logged in as: {{ username }}  <a href="{% url 'Repertoire:Logout' %}">  Logout</a>
	{% else %}

	{% csrf_token %}
	Login:<input type="text" name="username">
	Password:<input type="password" name="password">
	<input type="submit" value="Login">
	{% endif %}

	</form>

</div>
	
	{% if loggedin %}
		</br>

	<form action="{% url 'Performances:test' %}" method='post'>
	{% csrf_token %}
	<label for="Performances">Choose a performance: </label>
	<select onchange="this.form.submit()" name="Performances">
			{% for Performance in Performances %}
		    <option value="{{ Performance }}" {% if Performance == CurrentSelection %}selected{% endif%}>{{Performance}}</option>
			{% endfor %}
	</select>		
	
	</form>
	
	</br></br>

	<ul>
		{% for song in Songs %}
		    <li>{{ song }}</li>
		{% endfor %}
	</ul>

	{% endif %}

</body>
</html>

Repertoire/templates/Repertoire/AddSong.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/styles.css?v=1.0">

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>

<body>
</body>
</html>
	
	</br>
	{% if error_message %}
	Error
	{% endif %}
	

	</br>
	<br>


	<form action="{% url 'Repertoire:AddSong' %}" method='post'>
	{% csrf_token %}
	Song Name:<input type="text" name="SongName"><br>
	<input type="submit" value="Add Song">

	</form>

	<form>
	
	</form>



  <!-- <script src="js/scripts.js"></script> -->


</body>
</html>

Repertoire/templates/Repertoire/repertoire.html
{% load static %}

<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Repertoar</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="{% static 'Repertoire/style.css' %}" />

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>

<body>
</body>
</html>


<div class="header">


	<form action="{% url 'Repertoire:Login' %}" method='post'>
	
	{% if loggedin %}
		Logged in as: {{ username }}  <a href="{% url 'Repertoire:Logout' %}">  Logout</a>
	{% else %}

	{% csrf_token %}
	Login:<input type="text" name="username">
	Password:<input type="password" name="password">
	<input type="submit" value="Login">
	{% endif %}

	</form>

</div>
	
	{% if loggedin %}
	</br></br>

	<ul>
		{% for song in songs %}
		    <li>{{ song }}</li>
		{% endfor %}
	</ul>


	<form action="{% url 'Repertoire:AddSong' %}" method='post'>
	{% csrf_token %}
	Song Name:<input type="text" name="SongName"><br>
	<input type="submit" value="Add Song">

	</form>
	{% endif %}


  <!-- <script src="js/scripts.js"></script> -->


</body>
</html>